apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azdev-rb-[ServiceAccountName]-admin-on-[Namespace]
  namespace: [Namespace]
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: [ServiceAccountName]
  namespace: [Namespace]
