ingress:
  enabled: true
  className: nginx
  path: /oauth2
  pathType: Prefix
  hosts:
    - [ApplicationHostname]

  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: [CertClusterIssuerName]
    nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
  tls:
    - secretName: [ApplicationName]-oauth2-proxy-ingress-tls-secret
      hosts:
        - [ApplicationHostname]

proxyVarsAsSecrets: true

config:
  cookieName: [CookieName]
  clientID: [ClientID]
  clientSecret: [ClientSecret]
  cookieSecret: [CookieSecret]
resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

extraArgs:
  provider: oidc
  azure-tenant: [TenantId] # Azure AD OAuth2 Proxy application Tenant ID
  pass-access-token: true
  email-domain: "*"
  upstream: file:///dev/null
  http-address: 0.0.0.0:4180
  oidc-issuer-url: https://login.microsoftonline.com/[TenantId]/v2.0

podLabels:
  application: [ApplicationName]-oauth2-proxy
customLabels:
  application: [ApplicationName]-oauth2-proxy

replicaCount: 1
