name: pluto-gha

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  pluto-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Pluto
        uses: FairwindsOps/pluto/github-action@master

      - name: Run Kubernetes API deprecations validation with Pluto
        run: |
          pluto detect-files -d scripts/kubernetes/pluto/cicd-github/yaml-templates --ignore-deprecations --ignore-removals
          helm template "scripts/kubernetes/pluto/cicd-github/helm/testapp" -f "scripts/kubernetes/pluto/cicd-github/helm/testapp/values.yaml" | pluto detect - -o markdown --ignore-deprecations --ignore-removals
